swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '2.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v2
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      #produces:
       # - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /transactions/:
    get:
      tags:
        - Transactions
      summary: Returns transactions history
      description: Retrieve all transactions for the current month
      produces:
        - application/json
      parameters: []
      security:
      - Bearer: []
      responses:
        '200':
          description: Success. List of transactions loading.
          schema:
            type: array
            items:
              type: object
              properties:
                id:
                  type: string
                date:
                  type: string
                  format: date-time
                description:
                  type: string
                amount:
                  type: number
                balance:
                  type: number
        '401':
          description: Invalid Fields or missing token.
        '403':
          description: Unauthorized.  
        '500':
          description: Internal Server Error
  /transactions/{transactionId}:
    get:
      tags:
        - Transactions
      summary: Returns a specific transaction
      description: Retrieve a specific transaction
      produces:
        - application/json
      parameters: []
      security:
      - Bearer: []
      responses:
        '200':
          description: Success. List of transactions loading.
          schema:
            type: object
            properties:
              id:
                type: string
              date:
                type: string
                format: date-time
              description:
                type: string
              amount:
                type: number
              balance:
                type: number
              transaction_type:
                type: string
              category:
                type: string
              note:
                type: string
        '401':
          description: Invalid Fields or missing token.
        '403':
          description: Unauthorized.
        '404':
          description: Error request not find.
        '500':
          description: Internal Server Error
  /transactionOptions/{transactionId}:
    get:
      tags:
        - Transactions
      summary: Returns a specific transaction option
      description: Retrieve all options for a specific transaction
      produces:
        - application/json
      parameters: []
      security:
      - Bearer: []
      responses:
        '200':
          description: Success. List of transaction's options loading.
          schema:
            type: object
            properties:
              id:
                type: string
              transactionId:
                type: string
              transaction_type:
                type: string
              category:
                type: string
              note:
                type: string
        '401':
          description: Invalid Fields or missing token.
        '403':
          description: Unauthorized.
        '404':
          description: Error, request not find.
        '500':
          description: Internal Server Error
  /transactionOptions:
    post:
      tags:
        - Transactions
      summary: create a new category and note for a specific transaction
      description: create a new category and note for a specific transaction
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: transaction options Payload
          required: true
          schema:
            $ref: '#/definitions/TransactionOptionsNew'
      security:
      - Bearer: []
      responses:
        '201':
          description: Success. List of transactions loading.
          schema:
            type: object
            properties:
              id:
                type: string
              transactionId:
                type: string
              transaction_type:
                type: string
              category:
                type: string
              note:
                type: string
        '401':
          description: Invalid Fields or missing token.
        '403':
          description: Unauthorized.  
        '500':
          description: Internal Server Error    
  /transactionOptions/{TransactionOptionsId}:
    put:
      tags:
        - Transactions
      summary: Update or add informations of a specific transaction.
      description: allow to modify informations a specific transaction.
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: path
          name: transactionOptionsId
          description: transaction's ID to modify..
          required: true
          type: integer
        - in: body
          name: body
          description: transaction options Payload
          required: true
          schema:
            $ref: '#/definitions/TransactionOptionsNew'
      security:
        - Bearer: []
      responses:
        '200':
          description: Informations successfully modified.
        '401':
          description: Invalid Fields or missing token.
        '403':
          description: Unauthorized.
        '404':
          description: Error, request not find.
        '500':
          description: Internal Server Error
    delete:
      tags:
        - Transactions
      summary: Delete informations of a specific transaction.
      description: allow to delete some informations of a specific transaction.
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: path
          name: transactionId
          description: transaction's informations' ID to delete
          required: true
          type: integer
      security:
        - Bearer: []
      responses:
        '204':
          description: Informations successfully deleted.
        '401':
          description: Invalid Fields or missing token.
        '403':
          description: Unauthorized.
        '404':
          description: Error, request not find.
        '500':
          description: Internal Server Error
          
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header

definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
      userName:
        type: string
        description: user public name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      userName:
        type: string
  TransactionOptionsNew:
      properties:
              transactionId:
                type: string
              transaction_type:
                type: string
              category:
                type: string
              note:
                type: string
  TransactionOptions:
      properties:
              category:
                type: string
              note:
                type: string